### ISSUE TITLE
GraphQL - Queries to filter activities/notifications

### ISSUE THREAD

**Issue by DigbijayineeClara07** [turbot/tdk#100]

**Comment by omerosaienni** [comment]
I have added two more generic examples based off your example:
- list_policy_notifications_excluding_user.graphql
- list_policy_notifications_for_user.graphql

We should expand this out for the 3 or 4 main notification classes? 
https://turbot.com/v5/docs/concepts/notifications#notification-types

**Comment by omerosaienni** [comment]
List last 100 deleted resource is a good example

**Comment by omerosaienni** [comment]
We leave this file as this is a great example.
We need to change the name of the query.

ListS3BucketsControlsInAlarmState, something like this

Then we could create a more generic graphql example, with the token substitution
What we need to substitute is just the .

ListControlsInAlarmStateForResource <- Generic variety.
