### ISSUE TITLE
Calculated Policies - aws_sqs_approved returning incorrect value for not approved case

### ISSUE THREAD

**Issue by debabrat-git** [turbot/tdk#155]
- In `default.tfvars`: smart folder title need to be updated
- In `main.tf`: in Nunjucks template, policy value should be "Not approved" instead of ""Not Approved".

**Comment by omerosaienni** [comment]
Extra notes from Debu

> it is for sqs so we can keep like “SQS approved check” like that
> but now title is S3 Bucket Tagging Template
