### ISSUE TITLE
Calculated Policy - AWS > S3 > Bucket - Match tags on Bucket and CMK

### ISSUE THREAD

**Issue by luisffc** [turbot/tdk#210]
https://github.com/turbotio/expeditors/issues/296

**Comment by omerosaienni** [comment]
**Describe the solution you'd like**
We want to see if we can cross check two different resources.  For example, say I have an S3 bucket with PII data.  I would want that bucket encrypted with a kms key which is specifically for encrypting PII data.  To achieve this, I would have a compliance tag on my S3 bucket classifying it as PII as well as a compliance tag on my kms key classifying it as a key for encrypting PII data.  I’d want to be able to check that the compliance tag value on the S3 bucket matches the compliance tag value on the kms key and return compliant if they are the same. 

Scenario 1:

    Given: The initial context at the beginning of the scenario, in one or more clauses.

    When: The event that triggers the scenario.

    Then: The expected outcome, in one or more clauses.
