### ISSUE TITLE
Calculated Policy - Azure > Resource Group > Tags > Template

### ISSUE THREAD

**Issue by luisffc** [turbot/tdk#221]
https://github.com/turbotio/expeditors/issues/338

**Comment by choxie** [comment]
https://github.com/turbotio/expeditors/issues/367

new github issue for feature request. adding resource groups as part of the hierarchy of subscription -> service -> resource default tagging templates

**Comment by omerosaienni** [comment]
WIP branch that hasn't been submitted for review. 

@luisffc what do you want to do with this?

**Comment by omerosaienni** [comment]
No feedback and PR is closed
