### ISSUE TITLE
Custom mods - Implement a Control Framework for Dunder Mifflin (DMI)

### ISSUE THREAD

**Issue by luisffc** [turbot/tdk#274]
Implement a sample set of custom mods for the fictional company Dunder Mifflin
https://github.com/turbotio/turbot-mods/wiki/Sample-Custom-Mod---Dunder-Mifflin-(DMI)-Control-Framework

**Comment by omerosaienni** [comment]
Before AJ left, I asked him to have a discussion with John and David to see if this was still required. 

He said it was not. 

I will close the ticket but I will **NOT** delete the branch. 

@luisffc keep the branch open as you will never know if we will need to use this.
@e-gineer are you okay with me closing this issue?
