### ISSUE TITLE
Deployment script for v3 account removal CF template

### ISSUE THREAD

**Issue by alinder** [turbot/tdk#293]
It would be helpful for us to have a deployment script to be able to run multiple account removal CF templates at once.  Siemens has 215 accounts to remove from v3 and tends to do them in batches of 10.  That makes for a lot of repeated entries.  We would like a script where you could input the values for the CF template and then pass it a list of accounts.  This list will need to include both the Account ID and the AWS Account Number.  All the other values should remain the same for all the accounts in a single run of the script.  Once you've provided all the values, the script should deploy one CF template per account you've provided.  Please let me know if you have any questions.
[deploy_account_clean_public_subnet.cf.yml.zip](https://github.com/turbot/tdk/files/5402519/deploy_account_clean_public_subnet.cf.yml.zip)

**Comment by omerosaienni** [comment]
Sorry I missed this. This should normally go through ZenDesk and then I can prioritise and add the issue onto the board.

**Comment by omerosaienni** [comment]
Done offline
