### ISSUE TITLE
Calculated Policy - AWS EC2 Instance Approved Based on Image Tags

### ISSUE THREAD

**Issue by choxie** [turbot/tdk#504]
AWS EC2 Instance Approved Based on Image Tags

**Workspace Reference URL**
- [x] Create README.md (Required)
- [x] Add `outputs.tf` (If applicable)
- [x] Add `variables.tf` (Required)
- [x] Add `providers.tf` (Required)
- [x] Add `smart_folder.tf` (Required)
- [x] Policies end with `*_policies.tf` (Required)
- [x] Cloud specific resources are in own files
- [x] No customer data present

**Comment by vkumbha** [comment]
Ignore this comment. Testing slack
