### ISSUE TITLE
Base Line - Common configuration for importing AWS

### ISSUE THREAD

**Issue by DigbijayineeClara07** [turbot/tdk#55]
The AWS setup baseline terraform implements common configurations on your Turbot environment required to import an AWS account.

The Terraform script will do an account set up for AWS and installs the mods (if outdated or not installed)
- turbot
- turbot-iam
- aws
- aws-iam
- aws-cloudtrail
- aws-s3
- aws-kms
- aws-s3
- aws-sns
- aws-cloudwatch
- aws-events

**Comment by omerosaienni** [comment]
No longer required
